#:schema node_modules/wrangler/config-schema.json
name = "tbreak-app"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DATABASE"
database_name = "STATS"
database_id = "45e8bf6b-577c-4b69-bf31-f2feb7862a89"

[[kv_namespaces]]
binding = "CACHE"
id = "7e9aa78fc90f42a78e1a4690f0f313a9"
